<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerE5JgySb\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerE5JgySb/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerE5JgySb.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerE5JgySb\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerE5JgySb\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'E5JgySb',
    'container.build_id' => '494ac320',
    'container.build_time' => 1565968047,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerE5JgySb');
