<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWAxt6Y7\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWAxt6Y7/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWAxt6Y7.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWAxt6Y7\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerWAxt6Y7\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'WAxt6Y7',
    'container.build_id' => 'fe9863d8',
    'container.build_time' => 1566468714,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWAxt6Y7');
